#!/bin/bash
shopt -s expand_aliases

# Determine the installation directory
ALIS_DIR="$HOME/.local/alis"

# Includes
source "$ALIS_DIR/src/utils.sh"
source "$ALIS_DIR/src/functions.sh"

### Option Processing ###
while getopts ":v:-:" opt; do
    case $opt in
        -)
            case ${OPTARG} in
                help)
                    printHelp
                    exit 0
                    ;;
                *)
                    echo "Invalid option: --${OPTARG}" >&2
                    exit 1
                    ;;
            esac
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
        ?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
    esac
done

### Arg Processing ###
# If no args are supplied, or they called help or --help display the help message
if [ -z "$1" ] || [ "$1" == "help" ]; then
  printHelp
elif declare -F "$1" > /dev/null; then
    "$@"
    exit 0
else
  # Otherwise, attempt to run the specified script if its in bin
  if [ -f "$ALIS_DIR/bin/$1" ]; then
    echo 'runnin'
    # Run,
    run "$1" "${@:2}"

   #  if it exists OK then print success, fail otherwise
    if [ $? -eq 0 ]; then
      echo
      success "ALIS content - script success"
    else
      echo
      error "ALIS is sad - something went wrong"
    fi
  else
    echo 'sourcing'
    # Source all the aliases in the /aliases directory
    source "$ALIS_DIR/aliases/aliases"

    # If the first argument is an alias, it will now be a function in scope of this script
    if [ -n "$(type -t $1)" ]; then
      # If the alias is found, run it with arguments, stripping the first as its redudant now, and dont include if empty
      command=$1
      echo $command "$@"
      shift
      $command "$@"
      exit 0
    else
      # If the alias is not found, print an error message
      error "ALIS is sad - script or alias '$1' does not exist."
      exit 1
    fi
  fi
fi